# See https://docs.platformio.org/en/latest/manifests/library-json/fields/build/extrascript.html
Import("env")
from os.path import join, realpath, exists, isdir, isfile
import json
import os

# Base srcFilter. Cannot be set in library.json.
src_filter = [
    "+<resources>",
    "+<locale>",
    "+<source>"
]

has_berry = False

for item in env.get("CPPDEFINES", []):
    # Add generated view directory to include path dependending on VIEW_* macro
    if isinstance(item,str) and item.startswith("VIEW_"):
        view = f"ui_{item[5:]}".lower()  # Ex value: "ui_320x240"
        env.Append(CPPPATH=[realpath(join("generated", view))])
        src_filter.append(f"+<generated/{view}>")
    # Add portduino directory to include path dependending on ARCH_PORTDUINO macro
    elif item == "ARCH_PORTDUINO":
        env.Append(CPPPATH=[realpath("portduino")])
        src_filter.append("+<portduino>")
    # Check for Berry scripting support
    elif item == "HAS_APP_FRAMEWORK" or (isinstance(item, tuple) and item[0] == "HAS_APP_FRAMEWORK"):
        has_berry = True

# Berry scripting support
if has_berry:
    # Add Berry vendor source directory to include path so berry.h and berry_conf.h are found
    berry_vendor_dir = realpath(join("source", "berry", "vendor"))
    env.Append(CPPPATH=[berry_vendor_dir])
    # Generate built-in apps from apps/ directory
    apps_dir = realpath("apps")
    generated_dir = realpath(join("generated", "builtin_apps"))
    generated_file = join(generated_dir, "generated_builtin_apps.cpp")

    os.makedirs(generated_dir, exist_ok=True)

    embedded_strings = ""
    manifest_entries = ""
    app_count = 0

    if isdir(apps_dir):
        for app_dir_name in sorted(os.listdir(apps_dir)):
            app_path = join(apps_dir, app_dir_name)
            manifest_file = join(app_path, "app.json")

            if not isdir(app_path) or not isfile(manifest_file):
                continue

            with open(manifest_file, "r") as f:
                try:
                    manifest = json.load(f)
                except json.JSONDecodeError:
                    continue

            app_name = manifest.get("name", "")
            app_version = manifest.get("version", "")
            app_author = manifest.get("author", "")
            app_entry = manifest.get("entry", "")

            if not app_name or not app_entry:
                continue

            entry_file = join(app_path, app_entry)
            if not isfile(entry_file):
                continue

            with open(entry_file, "r") as f:
                be_source = f.read()

            # Create safe C identifier
            app_id = app_dir_name.replace("-", "_").replace(" ", "_")

            # Escape for C string
            be_source_escaped = be_source.replace("\\", "\\\\").replace('"', '\\"').replace("\n", '\\n"\n    "')

            embedded_strings += f'static const char app_{app_id}_source[] =\n    "{be_source_escaped}";\n\n'

            # Embed icon PNG if specified in manifest
            icon_ptr = "nullptr"
            icon_size = "0"
            app_icon = manifest.get("icon", "")
            if app_icon:
                icon_file = join(app_path, app_icon)
                if isfile(icon_file):
                    with open(icon_file, "rb") as icon_f:
                        icon_bytes = icon_f.read()
                    byte_array = ",".join(f"0x{b:02x}" for b in icon_bytes)
                    embedded_strings += f"static const uint8_t app_{app_id}_icon[] = {{{byte_array}}};\n\n"
                    icon_ptr = f"app_{app_id}_icon"
                    icon_size = str(len(icon_bytes))
                    print(f"    Icon: {app_icon} ({len(icon_bytes)} bytes)")
                else:
                    print(f"  WARNING: App {app_dir_name}: icon file '{app_icon}' not found")

            # Capabilities
            caps = manifest.get("capabilities", [])
            caps_str = ",".join(caps) if caps else ""
            caps_literal = f'"{caps_str}"' if caps_str else "nullptr"

            manifest_entries += f'    {{"{app_name}", "{app_version}", "{app_author}", "{app_entry}", app_{app_id}_source, true, {icon_ptr}, {icon_size}, {caps_literal}}},\n'
            app_count += 1
            print(f"  Built-in app: {app_name} v{app_version} ({app_dir_name})")

    # Write generated file
    with open(generated_file, "w") as f:
        f.write(f"""// Auto-generated by extra_script.py - DO NOT EDIT
#ifdef HAS_APP_FRAMEWORK
#include "berry/BerryRuntime.h"

{embedded_strings}
static const BuiltinAppEntry builtinApps[] = {{
{manifest_entries}}};

const BuiltinAppEntry *getBuiltinApps(int &count)
{{
    count = {app_count};
    return builtinApps;
}}
#endif
""")
    print(f"  Generated {app_count} built-in app(s)")

    env.Append(CPPPATH=[generated_dir])
    src_filter.append(f"+<generated/builtin_apps>")

# Only `Replace` is supported for SRC_FILTER, not `Append` or `Prepend`
env.Replace(SRC_FILTER=src_filter)

# Dump construction environment (for debug purposes)
# print("meshtastic-device-ui Library ENV:")
# print(env.Dump())
