# GenerateApps.cmake - Convert apps/ directory into embedded C source
# Scans apps/ subdirectories for app.json manifests and .be source files,
# generates a C++ source file with embedded string constants.

set(APPS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/apps)
set(GENERATED_APPS_FILE ${CMAKE_CURRENT_BINARY_DIR}/generated_builtin_apps.cpp)

# Collect all app directories
file(GLOB APP_DIRS RELATIVE ${APPS_DIR} ${APPS_DIR}/*)

set(EMBEDDED_STRINGS "")
set(MANIFEST_ENTRIES "")
set(APP_COUNT 0)

foreach(APP_DIR ${APP_DIRS})
    set(APP_PATH ${APPS_DIR}/${APP_DIR})
    set(MANIFEST_FILE ${APP_PATH}/app.json)

    if(EXISTS ${MANIFEST_FILE})
        # Read manifest
        file(READ ${MANIFEST_FILE} MANIFEST_CONTENT)

        # Extract fields from JSON using regex
        string(REGEX MATCH "\"name\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"" _match "${MANIFEST_CONTENT}")
        set(APP_NAME "${CMAKE_MATCH_1}")

        string(REGEX MATCH "\"version\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"" _match "${MANIFEST_CONTENT}")
        set(APP_VERSION "${CMAKE_MATCH_1}")

        string(REGEX MATCH "\"author\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"" _match "${MANIFEST_CONTENT}")
        set(APP_AUTHOR "${CMAKE_MATCH_1}")

        string(REGEX MATCH "\"entry\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"" _match "${MANIFEST_CONTENT}")
        set(APP_ENTRY "${CMAKE_MATCH_1}")

        if(APP_NAME AND APP_ENTRY)
            # Read the entry .be file
            set(ENTRY_FILE ${APP_PATH}/${APP_ENTRY})
            if(EXISTS ${ENTRY_FILE})
                file(READ ${ENTRY_FILE} BE_SOURCE)

                # Create a safe C identifier from the app directory name
                string(MAKE_C_IDENTIFIER ${APP_DIR} APP_ID)

                # Escape the Berry source for C string embedding
                string(REPLACE "\\" "\\\\" BE_SOURCE "${BE_SOURCE}")
                string(REPLACE "\"" "\\\"" BE_SOURCE "${BE_SOURCE}")
                string(REPLACE "\n" "\\n\"\n    \"" BE_SOURCE "${BE_SOURCE}")

                # Generate embedded string constant
                string(APPEND EMBEDDED_STRINGS
                    "static const char app_${APP_ID}_source[] =\n    \"${BE_SOURCE}\";\n\n")

                # Extract icon field and embed PNG if present
                string(REGEX MATCH "\"icon\"[[:space:]]*:[[:space:]]*\"([^\"]*)\"" _icon_match "${MANIFEST_CONTENT}")
                set(APP_ICON "${CMAKE_MATCH_1}")
                set(ICON_PTR "nullptr")
                set(ICON_SIZE "0")

                if(APP_ICON)
                    set(ICON_FILE ${APP_PATH}/${APP_ICON})
                    if(EXISTS ${ICON_FILE})
                        file(READ ${ICON_FILE} ICON_HEX HEX)
                        # Convert hex string to C byte array: "89504e..." -> "0x89,0x50,0x4e,..."
                        string(LENGTH "${ICON_HEX}" ICON_HEX_LEN)
                        set(ICON_BYTES "")
                        set(BYTE_IDX 0)
                        while(BYTE_IDX LESS ICON_HEX_LEN)
                            string(SUBSTRING "${ICON_HEX}" ${BYTE_IDX} 2 BYTE_HEX)
                            if(ICON_BYTES)
                                string(APPEND ICON_BYTES ",0x${BYTE_HEX}")
                            else()
                                set(ICON_BYTES "0x${BYTE_HEX}")
                            endif()
                            math(EXPR BYTE_IDX "${BYTE_IDX} + 2")
                        endwhile()
                        math(EXPR ICON_BYTE_COUNT "${ICON_HEX_LEN} / 2")
                        string(APPEND EMBEDDED_STRINGS
                            "static const uint8_t app_${APP_ID}_icon[] = {${ICON_BYTES}};\n\n")
                        set(ICON_PTR "app_${APP_ID}_icon")
                        set(ICON_SIZE "${ICON_BYTE_COUNT}")
                        message(STATUS "    Icon: ${APP_ICON} (${ICON_BYTE_COUNT} bytes)")
                    else()
                        message(WARNING "  App ${APP_DIR}: icon file '${APP_ICON}' not found")
                    endif()
                endif()

                # Generate manifest entry
                string(APPEND MANIFEST_ENTRIES
                    "    {\"${APP_NAME}\", \"${APP_VERSION}\", \"${APP_AUTHOR}\", \"${APP_ENTRY}\", app_${APP_ID}_source, true, ${ICON_PTR}, ${ICON_SIZE}},\n")

                math(EXPR APP_COUNT "${APP_COUNT} + 1")
                message(STATUS "  Found built-in app: ${APP_NAME} v${APP_VERSION} (${APP_DIR})")
            else()
                message(WARNING "  App ${APP_DIR}: entry file '${APP_ENTRY}' not found")
            endif()
        endif()
    endif()
endforeach()

message(STATUS "Generating ${APP_COUNT} built-in app(s)")

# Generate the C++ source file
file(WRITE ${GENERATED_APPS_FILE}
"// Auto-generated by GenerateApps.cmake - DO NOT EDIT
#ifdef HAS_APP_FRAMEWORK
#include \"berry/BerryRuntime.h\"

${EMBEDDED_STRINGS}
static const BuiltinAppEntry builtinApps[] = {
${MANIFEST_ENTRIES}};

const BuiltinAppEntry *getBuiltinApps(int &count)
{
    count = ${APP_COUNT};
    return builtinApps;
}
#endif
")
